version: "3.1"

services:
  # PostgreSQL DataBase
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 80:80
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres@example.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    depends_on:
      - db

  # BackEnd service running PoemOpenAPI.
  back:
    build: back/docker
    init: true
    volumes:
      - ./scripts:/opt/scripts:ro
      - ./back:/opt/back
      - ./openapi:/opt/openapi # cmd.sh will write spec.json here.

      # Use anonymous volumes cache data between on container config change.
      - back_cargo_target_dir:/opt/cargo_target_dir
    working_dir: /opt/back
    environment:
      - CARGO_TARGET_DIR=/opt/cargo_target_dir
      - DATABASE_URL=postgres://postgres:postgres@db/postgres
    command: cargo watch -- ./dev.sh
    ports:
      - 3000:3000
    depends_on:
      - db

  # Generate front reqwest client from spec.json.
  openapi:
    build: openapi/docker
    init: true
    volumes:
     - ./openapi:/opt/openapi
    working_dir: /opt/openapi
    command: /opt/openapi/dev.sh
    depends_on:
      - back

  # FrontEnd running leptos and generated reqwest client from openapi.
  front:
    build: front/docker
    init: true
    volumes:
      - ./front:/opt/front
      - ./openapi/out:/opt/openapi/out:ro

      # Use anonymous volumes to cache data on container config change.
      - front_cargo_target_dir:/opt/cargo_target_dir
      - front_trunk_cache:/root/.cache/trunk
    working_dir: /opt/front
    environment:
      - CARGO_TARGET_DIR=/opt/cargo_target_dir
      - CARGO_TERM_COLOR=always
    command: >
      trunk serve --port 8080 --address 0.0.0.0
        -w /opt/front -w /opt/openapi/out/spec.json.md5
        -i /opt/front/target
        --proxy-backend=http://back:3000/api/
    ports:
      - 8080:8080
    depends_on:
      - openapi

volumes:
  back_cargo_target_dir:
  front_cargo_target_dir:
  front_trunk_cache: