version: "3.1"

services:
  back:
    build: back/docker
    init: true
    volumes:
      - ./back:/opt/back
      - /opt/front/target
    working_dir: /opt/back
    command: cargo watch -- cargo run --color always
    ports:
      - 3000:3000

  front:
    build: front/docker
    init: true
    volumes:
      - ./front:/opt/front
      - /opt/front/target
    working_dir: /opt/front
    command: trunk serve --address 0.0.0.0
    ports:
      - 8080:8080
