version: "3.1"

services:
  back:
    build: back/docker
    init: true
    volumes:
      - ./scripts:/opt/scripts
      - ./back:/opt/back
      - ./openapi:/opt/openapi
      - /opt/back/target
    working_dir: /opt/back
    command: cargo watch -- ./docker/cmd.sh
    ports:
      - 3000:3000

  front:
    build: front/docker
    init: true
    volumes:
      - ./front:/opt/front
      - ./openapi/out:/opt/openapi/out
      - /opt/front/target
    working_dir: /opt/front
    command: trunk -v serve --port 8080 --address 0.0.0.0 -w /opt/front -w /opt/openapi/out/spec.json.md5 --proxy-backend=http://back:3000/api/
    ports:
      - 8080:8080

  openapi:
    build: openapi/docker
    init: true
    volumes:
     - ./openapi:/opt/openapi
    working_dir: /opt/openapi
    command: /opt/openapi/docker/cmd.sh
